version: "3.8"

services:
  # --- 1. PostgreSQL (Dữ liệu quan hệ: User, Ride, Payment) ---
  postgres:
    image: postgres:15-alpine
    container_name: cab_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: cab_booking_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cab_network

  # --- 2. MongoDB (Dữ liệu phi cấu trúc: Logs, Driver Location History) ---
  mongo:
    image: mongo:6.0
    container_name: cab_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - cab_network

  # --- 3. Redis (Caching & Pub/Sub cho Realtime GPS) ---
  redis:
    image: redis:alpine
    container_name: cab_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cab_network

  # --- 4. Zookeeper (Quản lý Kafka Broker) ---
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: cab_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - cab_network

  # --- 5. Kafka (Message Broker - Trái tim của Big Data) ---
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: cab_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Cấu hình để Kafka vừa chạy trong Docker vừa truy cập được từ Localhost (NodeJS bên ngoài)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - cab_network

# --- Quản lý Volumes (Để dữ liệu không bị mất khi tắt Docker) ---
volumes:
  postgres_data:
  mongo_data:

# --- Quản lý Network (Để các service nhìn thấy nhau) ---
networks:
  cab_network:
    driver: bridge
